apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: cmsaws
spec:
  selector:
    app: elasticsearch
  ports:
    - name: elasticsearch
      protocol: TCP
      port: 9200
      targetPort: 9200
  type: ClusterIP
