apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: cmsaws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      automountServiceAccountToken: false
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
          imagePullPolicy: IfNotPresent
          env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
          ports:
            - containerPort: 9200
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
              ephemeral-storage: "512Mi"
            limits:
              memory: "1Gi"
              ephemeral-storage: "1Gi"
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: elasticsearch-pvc
