apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-user
  namespace: cmsaws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-user
  template:
    metadata:
      labels:
        app: frontend-user
    spec:
      automountServiceAccountToken: false
      containers:
        - name: frontend-user
          image: newsflow/cmsaws-frontend-user:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
              ephemeral-storage: "128Mi"
            limits:
              memory: "256Mi"
