apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: cmsaws
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: newsflow
  DB_URL: jdbc:postgresql://postgres:5432/newsflow
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  ELASTIC_URL: http://elasticsearch:9200
